name: Run Jupyter Notebook and Create Release

on:
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install `uv`
      run: |
        pip install uv

    - name: make venv with uv
      run: | 
        uv venv

    - name: Activate venv and Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Run Jupyter Notebook
      run: |
        source .venv/bin/activate
        jupyter nbconvert --to notebook --execute omim_vs_orphanet_comparison.ipynb --output omim_vs_orphanet_comparison_output.ipynb

    - name: Get Date for Release Tag
      run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.DATE }}
        files: |
          output/*
        generate_release_notes: true
        draft: true